### ISSUE TITLE
Power_Disc and Power_Cont output

### ISSUE THREAD

**Issue by faskij** [suke18/POWSC#3]
Hello,

My name is Joe and I am interested in your POWSC package. I most interested in using this package to estimate the sample size needed between two treatment groups (control vs. treated) for scRNA-seq experiments. With that, I have some questions:

1) What is the differenct between Power_Disc() and Power_Cont() in terms of how they analyze power.
2) The out put of both functions is a little more complex than just a simple numeric estimate of power. Could you tell me what the abbreviations stand for (CD, FD, TD)? Also, why are they broken down into five intervals between 0 and 1? Lastly, what are the FDR.marginal and power.marginal output?

I am currently a graduate student studying biostatistics so please bear with me as I am new to interpreting scRNA-seq data analysis.

**Comment by suke18** [comment]
Hello, 

Thanks for your interest. 

1. These two functions estimate two types of powers in scRNA-seq. These two types corresponding to the discrete case and the continuous case. 
2. These abbreviations are well-explained in the https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/btaa607/5866544. RD: Recovered DE; FD: false discovery; CD: called DE; FN: false negative; TN: true negative. CN: called non-DE. Because we want to assess the stratified power which is different traditional understanding of the overall power. As the name implies, they output the FDR marginal calculation. 

I encourage you to read the original paper which can help you to understand most of the concept in scRNA-seq analysis especially for DE and power analysis. 

Please let me know if you need more. 


Thanks,
Kenong
